### PR TITLE
Support ferrum 0.16

### PR DESCRIPTION
**Pull request by le0pard**

### CODE REVIEW

**Comment by route** [comment]
Thanks, surprisingly one test is failing, and I tried to rerun it with no luck. I’ll merge and check how it goes in master

**Comment by le0pard** [comment]
@route looks like CI stuck, working already > 3 hours

**Comment by arjun810** [comment]
It'd be helpful to release a new gem version with this, as the previous one is locked.

**Comment by route** [comment]
When it’s time

**Pull request merged**
